"""
Prune-then-quantize test on Qwen3.8-27B — comparing ternary against int4,
informed by two real external data points:

  1. weight_quantization_findings.md (this repo): ternary PTQ on code-minilm
     (22M params) collapsed accuracy to random chance (50%), and mixed
     precision (INT8 attn + ternary FFN) was WORSE than uniform ternary.
     That doc flags two untested angles: does scale help, and does
     pruning-before-quantizing change anything.

  2. DeepSeek V4's real, production FP4 QAT: they apply their most
     aggressive quantization (FP4, 16 levels) only to MoE expert weights
     + one indexer path, keep everything else at FP8, and train the model
     to tolerate it (QAT, not PTQ). Notably, nobody with that scale of
     infrastructure went all the way to ternary (3 levels) — they stopped
     at 4-bit. That's a real signal about where the practical floor is.

IMPORTANT SCOPE NOTE: this script does PTQ (post-training quantization),
NOT DeepSeek-style QAT. True QAT means training with quantization simulated
during gradient updates over real steps — a much bigger project (needs a
training loop, real data, many steps). What this DOES test, honestly: does
int4 (DeepSeek's validated floor) survive PTQ where ternary didn't, on the
same pruned base, at much larger scale (27B vs 22M) than previously tested.

MEMORY NOTE: Qwen3.8-27B in bf16 is 55.58GB. This machine has 32GB RAM +
8GB VRAM = 40GB combined — the model does NOT fit entirely in fast memory.
Uses accelerate's device_map="auto" with disk offload so it actually loads
instead of OOMing. This makes each condition slow (real disk I/O per
layer), not a quick add.

Four conditions, model reloaded fresh for each (avoids stacked in-place
modification bugs, and matches the reality that we can't cheaply keep a
spare unmodified copy of pruned layers in RAM either):
  (a) baseline bf16 -- no changes
  (b) FFN pruned 30% only -- isolates pruning's own effect
  (c) FFN pruned 30% + ternary-quantized survivors
  (d) FFN pruned 30% + int4-quantized survivors (NF4, via bitsandbytes) --
      the DeepSeek-informed comparison point

Usage:
  python qwen27b_prune_ternary_test.py --model-path C:/models/qwen3.8-27B-bf16
  python qwen27b_prune_ternary_test.py --model-path ... --offload-folder D:/offload
"""
import argparse
import gc
import os
import shutil
import time

import torch
import torch.nn as nn

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

PRUNE_FRAC = 0.3
FFN_NAME_PARTS = ("gate_proj", "up_proj", "down_proj")   # Qwen MLP layer names

EVAL_TEXT = """
The history of computing is a story of abstraction layers built one on top
of another. Early machines were programmed by physically rewiring circuits,
a process that took hours or days for even simple calculations. The
invention of stored-program architecture changed this fundamentally --
instructions could now be data, manipulated and generated by other
programs. This single idea underlies nearly everything that followed:
compilers that translate human-readable code into machine instructions,
operating systems that abstract away hardware details, and virtual
machines that simulate entirely different computers in software.

Each layer of abstraction trades some raw performance for a large gain in
human productivity and correctness. A programmer writing in a high-level
language accepts that their code will run slower than hand-tuned assembly,
in exchange for code that is easier to write, read, and verify. This
trade-off has proven durable across seven decades of computing history,
even as the specific technologies at each layer have been replaced many
times over. The pattern repeats at every scale, from individual functions
to entire distributed systems spanning thousands of machines.
""".strip()


def materialize(module):
    """Force accelerate to load real data for a module that's currently a
    meta-device placeholder (disk/cpu-offloaded, not yet touched by a real
    forward pass). Real fix for 'Tensor.item() cannot be called on meta
    tensors' / LoftQ's 'Cannot copy out of meta tensor' -- accelerate's own
    AlignDevicesHook.pre_forward() does exactly this materialization
    internally before every real forward call (that's why Condition A's
    forward pass worked fine with meta tensors present); we just need to
    trigger it manually here since we're modifying weights directly, not
    running a forward pass."""
    if module.weight.device.type == "meta" and hasattr(module, "_hf_hook"):
        module._hf_hook.pre_forward(module)


def prune_ffn_magnitude(module, frac):
    if frac <= 0.0:
        return 0
    materialize(module)
    with torch.no_grad():
        w = module.weight.data
        flat = w.abs().flatten()
        k = int(flat.numel() * frac)
        if k == 0:
            return 0
        thresh = torch.kthvalue(flat, k).values
        mask = w.abs() > thresh
        w.mul_(mask)
        return int((~mask).sum().item())


def ternary_quantize_inplace(module, thresh=0.7):
    materialize(module)
    with torch.no_grad():
        w = module.weight.data
        nonzero = w[w != 0]
        if nonzero.numel() == 0:
            return
        scale = nonzero.abs().mean()
        t = thresh * scale
        trit = torch.where(w > t, torch.ones_like(w),
               torch.where(w < -t, -torch.ones_like(w), torch.zeros_like(w)))
        module.weight.data = (trit * scale).to(w.dtype)


def int4_quantize_inplace(module):
    """Round-trip through bitsandbytes' NF4 (real, tested int4 scheme --
    same family DeepSeek's FP4 belongs to, 16 representable levels vs
    ternary's 3) -- quantize then immediately dequantize, so the weight
    tensor ends up holding what the model would actually see at int4
    precision, still stored in the original dtype for the forward pass."""
    import bitsandbytes.functional as bnbF
    materialize(module)
    with torch.no_grad():
        w = module.weight.data
        orig_dtype = w.dtype
        orig_shape = w.shape
        w_gpu = w.to(device=device, dtype=torch.float16).contiguous()
        packed, quant_state = bnbF.quantize_4bit(w_gpu, quant_type="nf4")
        dequant = bnbF.dequantize_4bit(packed, quant_state)
        module.weight.data = dequant.reshape(orig_shape).to(device="cpu", dtype=orig_dtype)
        del w_gpu, packed, dequant
        torch.cuda.empty_cache()


def is_ffn_linear(name, module):
    return isinstance(module, nn.Linear) and any(p in name for p in FFN_NAME_PARTS)


# ── Raw-tensor variants for direct checkpoint surgery ──────────────────
# The module-based functions above (materialize + modify a loaded,
# accelerate-hook-managed nn.Linear) hit two real bugs: unbounded GPU
# memory growth from repeatedly calling pre_forward() with no matching
# release across 192 FFN layers (OOM'd at 20GB+ against an 8GB card), and
# a device-mismatch crash when a manually CPU-placed tensor didn't match
# what the hook's own bookkeeping expected for the next real forward pass.
# These operate on plain tensors loaded straight from safetensors files --
# no hooks, no meta-device placeholders, no device-tracking to fight.

def prune_tensor_magnitude(tensor, frac):
    if frac <= 0.0:
        return 0
    with torch.no_grad():
        flat = tensor.abs().flatten()
        k = int(flat.numel() * frac)
        if k == 0:
            return 0
        thresh = torch.kthvalue(flat, k).values
        mask = tensor.abs() > thresh
        tensor.mul_(mask)
        return int((~mask).sum().item())


def ternary_quantize_tensor(tensor, thresh=0.7):
    with torch.no_grad():
        nonzero = tensor[tensor != 0]
        if nonzero.numel() == 0:
            return
        scale = nonzero.abs().mean()
        t = thresh * scale
        trit = torch.where(tensor > t, torch.ones_like(tensor),
               torch.where(tensor < -t, -torch.ones_like(tensor), torch.zeros_like(tensor)))
        tensor.copy_((trit * scale).to(tensor.dtype))


def int4_quantize_tensor(tensor):
    import bitsandbytes.functional as bnbF
    with torch.no_grad():
        orig_dtype = tensor.dtype
        orig_shape = tensor.shape
        w_gpu = tensor.to(device=device, dtype=torch.float16).contiguous()
        packed, quant_state = bnbF.quantize_4bit(w_gpu, quant_type="nf4")
        dequant = bnbF.dequantize_4bit(packed, quant_state)
        tensor.copy_(dequant.reshape(orig_shape).to(device="cpu", dtype=orig_dtype))
        del w_gpu, packed, dequant
        torch.cuda.empty_cache()


def prune_and_quantize_checkpoint(src_dir, dst_dir, prune_frac, quant_mode):
    """Process each safetensors shard directly, save a new checkpoint.
    Copies non-weight files (config, tokenizer, index) unchanged."""
    from safetensors.torch import load_file, save_file

    os.makedirs(dst_dir, exist_ok=True)
    all_files = os.listdir(src_dir)
    shard_files = sorted(f for f in all_files if f.endswith(".safetensors"))
    other_files = [f for f in all_files if not f.endswith(".safetensors")]

    for f in other_files:
        src = os.path.join(src_dir, f)
        if os.path.isfile(src):
            shutil.copy2(src, os.path.join(dst_dir, f))

    total_zeroed = total_params = 0
    t0 = time.time()
    for i, shard_name in enumerate(shard_files):
        tensors = load_file(os.path.join(src_dir, shard_name))
        for name, tensor in tensors.items():
            if tensor.ndim == 2 and any(p in name for p in FFN_NAME_PARTS):
                total_params += tensor.numel()
                total_zeroed += prune_tensor_magnitude(tensor, prune_frac)
                if quant_mode == "ternary":
                    ternary_quantize_tensor(tensor)
                elif quant_mode == "int4":
                    int4_quantize_tensor(tensor)
        save_file(tensors, os.path.join(dst_dir, shard_name), metadata={"format": "pt"})
        print(f"    shard {i+1}/{len(shard_files)} done ({time.time()-t0:.0f}s elapsed)")
        del tensors
        gc.collect()

    sparsity = total_zeroed / total_params if total_params else 0.0
    print(f"  checkpoint surgery done in {time.time()-t0:.0f}s, sparsity={sparsity*100:.1f}%")
    return sparsity


def compute_perplexity(model, tokenizer, text):
    model.eval()
    enc = tokenizer(text, return_tensors="pt")
    # Match the first parameter's device -- accelerate may have placed the
    # embedding layer on cuda:0, cpu, or disk-backed; input_ids follow it.
    first_device = next(model.parameters()).device
    enc = {k: v.to(first_device) for k, v in enc.items()}
    with torch.no_grad():
        out = model(**enc, labels=enc["input_ids"])
    return torch.exp(out.loss).item(), out.loss.item()


def load_model(model_path, offload_folder):
    from transformers import AutoModelForCausalLM, AutoTokenizer
    print(f"Loading {model_path} (disk-offloaded, model is 55.6GB > 40GB combined RAM+VRAM)...")
    t0 = time.time()
    tokenizer = AutoTokenizer.from_pretrained(model_path, trust_remote_code=True)
    model = AutoModelForCausalLM.from_pretrained(
        model_path,
        dtype=torch.bfloat16,
        device_map="auto",
        offload_folder=offload_folder,
        offload_state_dict=True,
        trust_remote_code=True,
        max_memory={0: "6GiB", "cpu": "13GiB"},
    )
    print(f"  loaded in {time.time()-t0:.0f}s, {sum(p.numel() for p in model.parameters()):,} params")
    return model, tokenizer


def unload(model):
    del model
    gc.collect()
    torch.cuda.empty_cache()


def run_condition_e_lora_recovery(model_path, offload_folder, train_steps=150):
    """
    Condition E: FFN pruned 30%, then LoRA adapters added via LoftQ init
    (bits=4) on those same FFN layers, fine-tuned with Muon for a short
    real recovery run on wikitext-2, then perplexity measured again.

    This is the genuine test of whether a PRINCIPLED recovery step --
    LoftQ init targets exactly the quantization error via SVD instead of
    random init, Muon is the 2025/26 optimizer already proven at production
    scale (Kimi K2, GLM-4.5) -- can close the gap that our own blind,
    all-at-once ternary QAT switch (loss spike at step 1125, never
    recovered) could not. Still a SHORT run (150 steps) on a small adapter,
    not a full production fine-tune -- real but modest in scope.
    """
    from peft import LoftQConfig, LoraConfig, get_peft_model
    from datasets import load_dataset

    print("\n" + "=" * 70)
    print("CONDITION E: FFN pruned 30% + LoRA (LoftQ int4 init) + Muon recovery fine-tune")
    print("=" * 70)

    model, tokenizer = load_model(model_path, offload_folder)

    ffn_layers = [(n, m) for n, m in model.named_modules() if is_ffn_linear(n, m)]
    total_zeroed = total_params = 0
    for name, module in ffn_layers:
        total_params += module.weight.numel()
        total_zeroed += prune_ffn_magnitude(module, PRUNE_FRAC)
    sparsity = total_zeroed / total_params if total_params else 0.0
    print(f"  pruned {len(ffn_layers)} FFN layers, sparsity={sparsity*100:.1f}%")

    print("  Adding LoRA adapters with LoftQ init (targets the quantization")
    print("  error via SVD, not random/zero init)...")
    loftq_config = LoftQConfig(loftq_bits=4)
    lora_config = LoraConfig(
        r=16, lora_alpha=32, lora_dropout=0.0,
        target_modules=list(FFN_NAME_PARTS),
        init_lora_weights="loftq", loftq_config=loftq_config,
        task_type="CAUSAL_LM",
    )
    model = get_peft_model(model, lora_config)
    trainable, total = model.get_nb_trainable_parameters()
    print(f"  LoRA adapters: {trainable:,} trainable / {total:,} total ({trainable/total*100:.4f}%)")

    print(f"  Loading wikitext-2 for a real {train_steps}-step recovery fine-tune...")
    ds = load_dataset("wikitext", "wikitext-2-raw-v1", split="train")
    texts = [t for t in ds["text"] if len(t.strip()) > 200][:train_steps]

    trainable_params = [p for p in model.parameters() if p.requires_grad]
    optimizer = torch.optim.Muon(trainable_params, lr=1e-4)

    model.train()
    t0 = time.time()
    for step, text in enumerate(texts):
        enc = tokenizer(text, return_tensors="pt", truncation=True, max_length=256)
        first_device = next(model.parameters()).device
        enc = {k: v.to(first_device) for k, v in enc.items()}
        out = model(**enc, labels=enc["input_ids"])
        loss = out.loss
        loss.backward()
        optimizer.step()
        optimizer.zero_grad()
        if step % 25 == 0:
            print(f"    step {step}/{len(texts)}  loss={loss.item():.4f}  ({time.time()-t0:.0f}s elapsed)")
    print(f"  fine-tuning done in {time.time()-t0:.0f}s")

    model.eval()
    ppl, loss_val = compute_perplexity(model, tokenizer, EVAL_TEXT)
    print(f"  Perplexity after recovery: {ppl:.3f}  (loss={loss_val:.4f})")

    unload(model)
    return ppl, loss_val, sparsity


def run_condition_f_temporal_prune(model_path, offload_folder, train_steps=150, ramp_fraction=0.67):
    """
    Condition F: same as E (LoftQ int4 init + Muon recovery), but the
    PRUNING fraction is temporally ramped from 0 -> PRUNE_FRAC across the
    first `ramp_fraction` of training steps, then held at PRUNE_FRAC for
    the remainder -- instead of applying the full 30% sparsity all at once
    before training starts (what E does).

    Directly implements this repo's own "fixable path" #2 from
    weight_quantization_findings.md: "Progressive threshold annealing --
    start with few weights quantized, anneal toward the target over
    epochs. Model adapts incrementally rather than all at once." Real,
    current external research (2026 QAT-scheduling papers) backs the same
    idea: schedule shape over training time measurably affects how well a
    model tolerates aggressive quantization/sparsity.

    LoftQ's own base-model quantization still happens once at setup (that
    part of the base can't be temporally ramped without reworking how
    LoftQ initializes) -- what's genuinely temporal here is the pruning
    schedule, re-applied at each step as training proceeds.
    """
    from peft import LoftQConfig, LoraConfig, get_peft_model
    from datasets import load_dataset

    print("\n" + "=" * 70)
    print("CONDITION F: temporal pruning ramp (0->30% over first 67% of steps) + LoftQ int4 + Muon")
    print("=" * 70)

    model, tokenizer = load_model(model_path, offload_folder)

    # Condition E prunes upfront, which materializes every FFN layer as a
    # side effect before LoftQ ever touches them. F doesn't prune upfront
    # (that's the whole point -- it's ramped during training), so LoftQ's
    # own init would hit the same meta-tensor crash unless we force
    # materialization explicitly first.
    for name, module in model.named_modules():
        if is_ffn_linear(name, module):
            materialize(module)

    print("  Adding LoRA adapters with LoftQ init (int4)...")
    loftq_config = LoftQConfig(loftq_bits=4)
    lora_config = LoraConfig(
        r=16, lora_alpha=32, lora_dropout=0.0,
        target_modules=list(FFN_NAME_PARTS),
        init_lora_weights="loftq", loftq_config=loftq_config,
        task_type="CAUSAL_LM",
    )
    model = get_peft_model(model, lora_config)
    trainable, total = model.get_nb_trainable_parameters()
    print(f"  LoRA adapters: {trainable:,} trainable / {total:,} total ({trainable/total*100:.4f}%)")

    # base_layer holds the actual frozen weight under each LoRA-wrapped module
    ffn_base_layers = [(n, m.base_layer) for n, m in model.named_modules()
                        if hasattr(m, "base_layer") and is_ffn_linear(n, m.base_layer)]

    print(f"  Loading wikitext-2 for a real {train_steps}-step recovery fine-tune...")
    ds = load_dataset("wikitext", "wikitext-2-raw-v1", split="train")
    texts = [t for t in ds["text"] if len(t.strip()) > 200][:train_steps]

    trainable_params = [p for p in model.parameters() if p.requires_grad]
    optimizer = torch.optim.Muon(trainable_params, lr=1e-4)
    ramp_steps = max(1, int(train_steps * ramp_fraction))

    model.train()
    t0 = time.time()
    last_sparsity = 0.0
    for step, text in enumerate(texts):
        target_frac = PRUNE_FRAC * min(1.0, step / ramp_steps)
        if abs(target_frac - last_sparsity) > 0.01:
            total_zeroed = total_params = 0
            for name, module in ffn_base_layers:
                total_params += module.weight.numel()
                total_zeroed += prune_ffn_magnitude(module, target_frac)
            last_sparsity = total_zeroed / total_params if total_params else 0.0

        enc = tokenizer(text, return_tensors="pt", truncation=True, max_length=256)
        first_device = next(model.parameters()).device
        enc = {k: v.to(first_device) for k, v in enc.items()}
        out = model(**enc, labels=enc["input_ids"])
        loss = out.loss
        loss.backward()
        optimizer.step()
        optimizer.zero_grad()
        if step % 25 == 0:
            print(f"    step {step}/{len(texts)}  loss={loss.item():.4f}  "
                  f"sparsity={last_sparsity*100:.1f}%  ({time.time()-t0:.0f}s elapsed)")
    print(f"  fine-tuning done in {time.time()-t0:.0f}s, final sparsity={last_sparsity*100:.1f}%")

    model.eval()
    ppl, loss_val = compute_perplexity(model, tokenizer, EVAL_TEXT)
    print(f"  Perplexity after recovery: {ppl:.3f}  (loss={loss_val:.4f})")

    unload(model)
    return ppl, loss_val, last_sparsity


def run_condition(model_path, offload_folder, label, prune_frac, quant_mode):
    """quant_mode: None, 'ternary', or 'int4'. When either is set, does
    direct checkpoint surgery on the safetensors files first (real tensors,
    no accelerate hooks involved -- see prune_and_quantize_checkpoint's
    docstring for why the in-memory hook-based approach was replaced),
    saves a temp modified checkpoint, loads THAT cleanly, measures, then
    deletes the temp checkpoint before returning (each is ~55GB, only ever
    one on disk at a time)."""
    print("\n" + "=" * 70)
    print(f"CONDITION: {label}")
    print("=" * 70)

    ckpt_dir = None
    load_path = model_path
    sparsity = 0.0
    if prune_frac > 0 or quant_mode:
        ckpt_dir = model_path.rstrip("/\\") + f"-tmp-{quant_mode or 'prune'}"
        if os.path.exists(ckpt_dir):
            shutil.rmtree(ckpt_dir)
        sparsity = prune_and_quantize_checkpoint(model_path, ckpt_dir, prune_frac, quant_mode)
        load_path = ckpt_dir

    model, tokenizer = load_model(load_path, offload_folder)
    ppl, loss = compute_perplexity(model, tokenizer, EVAL_TEXT)
    print(f"  Perplexity: {ppl:.3f}  (loss={loss:.4f})")
    unload(model)

    if ckpt_dir:
        shutil.rmtree(ckpt_dir, ignore_errors=True)

    return ppl, loss, sparsity


CONDITIONS = {
    "A": ("A) baseline bf16, no changes", dict(prune_frac=0.0, quant_mode=None)),
    "B": ("B) FFN pruned 30%, no quantization", dict(prune_frac=PRUNE_FRAC, quant_mode=None)),
    "C": ("C) FFN pruned 30% + ternary-quantized survivors", dict(prune_frac=PRUNE_FRAC, quant_mode="ternary")),
    "D": ("D) FFN pruned 30% + int4 (NF4) quantized survivors", dict(prune_frac=PRUNE_FRAC, quant_mode="int4")),
}


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--model-path", required=True)
    parser.add_argument("--offload-folder", default="C:/models/offload-tmp")
    parser.add_argument("--condition", required=True, choices=["A", "B", "C", "D", "E", "F"],
        help="Run exactly ONE condition per process invocation -- disk-offloaded loading "
             "twice in the same process segfaults (accelerate/CUDA state issue on Windows), "
             "so run_all.py shells out to a fresh process per condition instead.")
    parser.add_argument("--recovery-steps", type=int, default=150)
    parser.add_argument("--result-file", default=None,
        help="If set, write {ppl, loss, sparsity} as JSON to this path for run_all.py to collect.")
    args = parser.parse_args()

    if args.condition in CONDITIONS:
        label, kwargs = CONDITIONS[args.condition]
        ppl, loss, sparsity = run_condition(args.model_path, args.offload_folder, label, **kwargs)
    elif args.condition == "E":
        ppl, loss, sparsity = run_condition_e_lora_recovery(
            args.model_path, args.offload_folder, train_steps=args.recovery_steps)
    elif args.condition == "F":
        ppl, loss, sparsity = run_condition_f_temporal_prune(
            args.model_path, args.offload_folder, train_steps=args.recovery_steps)

    if args.result_file:
        import json
        with open(args.result_file, "w") as f:
            json.dump({"condition": args.condition, "ppl": ppl, "loss": loss, "sparsity": sparsity}, f)


if __name__ == "__main__":
    main()
